### PR TITLE
Fixing silent failure of missing required options

### LINKED ISSUE #60: Required options do not throw error
I'm using Vorpal with the reduced test case below:

```js
'use strict';

let cli = require('vorpal')();

cli
  .command('test')
  .description('reduced test case')
  .option('--required <val>', 'Should be a required value')
  .action(function(c) {
    console.log(c.options.required);
  });

cli.parse(process.argv);
```

```sh
node index test
```

This command's action should not execute using the given command, as no `--required` value was specified. According to the current source in lib/util.js:199, missing required options shows a message in the console along with help. This does not happen.

### PR DESCRIPTION
**Pull request by eliperelman**
Fixes #60.

### CODE REVIEW

**Comment by scotthovestadt** [comment]
+1

**Comment by dthree** [comment]
Great - thanks!

:+1:

**Comment by eliperelman** [comment]
Excellent, will this be on npm soon?

**Comment by dthree** [comment]
Just published - v1.4.1

**Pull request merged**
