### PR TITLE
Fixes multiple matching commands for autocomplete

### PR DESCRIPTION
**Pull request by jeff-1amstudios**
hey @dthree this is a small set of the autocomplete changes I made against a previous build a few months ago - I still see some of these problems in 1.10.10, this fixes those cases and adds tests to make sure we never regress

### CODE REVIEW

**Comment by dthree** [comment]
Thanks! :+1:

**Comment by jeff-1amstudios** [comment]
Would you be able to publish a new build to npm which includes this fix?
In the meantime I've been referencing this git revision in my package.json
and have had reports of failing installs because users didn't have git
installed.

thanks!
Jeff

**Comment by jeff-1amstudios** [comment]
Ping :)  Could you publish the latest build to npm with this fix?

**Comment by dthree** [comment]
Hey Jeff. Doing it now :)

**Comment by dthree** [comment]
Ok, this is published in `v1.11.1`.

**Comment by jeff-1amstudios** [comment]
great, thanks!

**Pull request merged**
