### PR TITLE
Added ability to cancel commands with CTRL + C

### PR DESCRIPTION
**Pull request by jackyjieliu**
CTRL + C will cancel a running command (if any running) by calling the cancel function registered and the cancel function on the promise if it exists

#45

### CODE REVIEW

**Comment by scotthovestadt** [comment]
Looks like the test is failing on older versions of node because we can't use ````const```` widely yet without Babel or other compilers.

**Comment by jackyjieliu** [comment]
Didn't realize i was using const.
Thanks for catching it

**Comment by scotthovestadt** [comment]
This looks great! Thanks.

**Comment by scotthovestadt** [comment]
@jackyjieliu See comments in the commit.

**Comment by scotthovestadt** [comment]
As discussed, the Vorpal action should be able to use ````this.cancel()```` internally to cancel itself. This should also emit the event.

**Comment by scotthovestadt** [comment]
Added ability to cancel commands with CTRL + C #45

**Pull request merged**
