### PR TITLE
Allow user to access the raw command string

### PR DESCRIPTION
**Pull request by ORESoftware**
Allow user to access the raw command string

### CODE REVIEW

**Comment by ORESoftware** [comment]
this is a really important feature for my use case, please consider merging this as soon as convenient, thank you

**Comment by ORESoftware** [comment]
@dthree @milesj  it would be really cool if you could help merge this PR, it's a feature I really need, and it's just a couple lines of code

**Comment by milesj** [comment]
I'm ok with this change, but I don't think I have access to publish a new version.

I also feel like this change would need to happen in other locations besides session.

**Comment by ORESoftware** [comment]
@milesj for now, this is sufficient for my needs, I don't think adding it to other places besides session is necessary, but it might add value too.

**Pull request merged**
