### PR TITLE
Auto-complete when typing piped commands #22

### PR DESCRIPTION
**Pull request by scotthovestadt**

### CODE REVIEW

**Comment by scotthovestadt** [comment]
Fails because of the linter.

**Comment by dthree** [comment]
Yeah - was missing a dev dep.

---

You're awesome. Thanks! :+1:

**Comment by dthree** [comment]
There were a few linting points you had that didn't conform to `xo`, but I fixed those. Published now :)

**Comment by scotthovestadt** [comment]
Sorry about that. Won't happen again, since I'll be able to lint. I was kind of guessing based on the surrounding code.

**Comment by dthree** [comment]
No probs :)

**Pull request merged**
