### PR TITLE
2.0 [WIP]

### PR DESCRIPTION
**Pull request by milesj**
The entire refactor that is v2.0.

### CODE REVIEW

**Comment by dthree** [comment]
Holy snap!

🎉 🎈 🔥 

Good work!

---

Give me a bit to look this over.

I want to make sure we didn't miss any other breaking changes we need to make before publishing. Was there anything else you were looking at?

**Comment by milesj** [comment]
Oh, this isn't done yet. Just throwing it up for progress :P

**Comment by newoga** [comment]
@milesj Are you accepting PRs for the `2.0` branch? I'd like to jump in and help if you're open to it. I see the branch is undergoing some heavy refactoring and don't want to get in the way if it'd be easier for your to work on it independently for a while.

If so, I'd probably start with fixing the existing eslint errors (which seem to be mostly flowtype annotation errors). It also might make sense for this project to maintain its own build configuration (I find it's a little friendlier/easier for contributors to get up to speed when the build configuration belongs to the repo or at least with an organization that the repo exists under). I can help with setting some of that up.

Ultimately I'd love to see what steps we'd need to take to get tests passing again (or at least the ones that test for behavior we want to keep).

Anyhow, let me know. Cheers!

**Comment by milesj** [comment]
@newoga Thanks for the interest! I'm definitely open to contributions as I can't put my full attention on the 2.0 branch. This is my current plan of action:

* Migrate remaining lib/ files to src/, while refactoring to ES2015+ and adding Flowtype. The last remaining lib/ files are rather difficult and time consuming to deal with.
* Rewrite all unit tests using Jest. I tried to keep the current tests runnable with the new source code, but it turned out to be quite troublesome, so we'll need to copy over the old unit tests into the new Jest tests and make sure they still run.
* Once these 2 major tasks are done, a final ESlint and Flowtype pass will be done.

From there, it's simply verifying everything works accordingly.

I have some commits to push up, but if you're interested in helping out, let me know and we can figure out the best action to take.

**Comment by newoga** [comment]
@milesj Awesome - yeah I'd be glad to help. 👍 

The plan sounds good to me. I started looking at it `2.0` late last night, but I'd probably spend sometime tonight familiarizing myself with the `master` branch as well just to get a better understanding where we came from. Let me know when you pushed up your latest commits and if you have any thoughts on areas where I should plug in.

**Comment by milesj** [comment]
@newoga I'm currently working on `ui` and `session` stuff, so if you'd like, you can do `autocomplete`. It's a bit isolated from the rest, so should be easier.

**Comment by dthree** [comment]
Do make sure you catch up on existing autocomplete issues, though. There's a few open.

👍

**Comment by milesj** [comment]
We should also remove the old autocomplete API.

**Comment by dthree** [comment]
Yes!

**Comment by newoga** [comment]
> @newoga I'm currently working on ui and session stuff, so if you'd like, you can do autocomplete. It's a bit isolated from the rest, so should be easier.

@milesj Sounds good! I'll take a look at the issues and code tonight.

**Comment by newoga** [comment]
> Do make sure you catch up on existing autocomplete issues, though. There's a few open.

> We should also remove the old autocomplete API.

@milesj @dthree I familiarized myself with many of the issues/history related to autocomplete. I also started reviewing/working on migrating `lib/autocomplete.js`.

For simplicity, I started to migrate `autocomplete.js` over with as much of existing implementation as possible (making necessary changes to fix eslint and flow errors along the way). I figured it would be easier to move the code as is first, then after I can look at refactoring/improving what is there to address the concerns/bugs raised in the github issues.

Let me know if that works for you two.

**Comment by milesj** [comment]
Works for me!

**Comment by E314c** [comment]
Whats the current status for this? Anything I can help with?

**Comment by milesj** [comment]
@E314c I've been a bit swamped with other projects, but hoping to get back on this soon.

**Comment by AdrieanKhisbe** [comment]
@milesj Any news?

**Comment by milesj** [comment]
Same response. Have some other projects I need to get out of the way first. About half way through them.

**Comment by AdrieanKhisbe** [comment]
Good luck with them then ! 😃 
(In case you need a hand, I could help)

**Comment by AdrieanKhisbe** [comment]
I have some improvement to vorpal in mind that are breaking changes.
Will open some issue for them as base of discussion, then build up PR toward this branch on some discussion has occurred.

Once open will post links there.

**Comment by Ore4444** [comment]
Hey, are you open for contributions on the 2.0 branch? I can help.

**Comment by milesj** [comment]
@Ore4444 This PR is so far out of date, might be best just to start over, and possibly write it in TypeScript. I don't really have time to do it, but I can review PRs.

**Comment by Ore4444** [comment]
@milesj I might actually take it upon myself to migrate Vorpal to TypeScript.
Should I work directly on top of master? Should I ignore any past discussions about roadmap and future of the project?

Should I open a focused PR with just TypeScript migration of all current functionality?

**Comment by milesj** [comment]
@Ore4444 I can cut a 2.0 TS branch in which you can submit PRs too.

**Comment by Ore4444** [comment]
@milesj cool, I'd like that.

My focus will be only on re-writing Vorpal in TypeScript without adding/changing any functionality.

Other than all tests having to pass, are there more things I need to keep in mind and validate before submitting the PR?

**Comment by milesj** [comment]
@Ore4444 Would also make sure the deps are up to date, and probably replace minimist with yargs.

I created the branch you can cut from: https://github.com/dthree/vorpal/tree/2.0-ts Might be easiest to submit PRs piece meal.

**Comment by Ore4444** [comment]
@milesJ Cool. I think I can't push to this branch. I get 403. Possible?

**Comment by milesj** [comment]
@Ore4444 You need to submit PRs to it, not push to it.

**Comment by Ore4444** [comment]
Yep, got it.

**Comment by ShadiestGoat** [comment]
Hey, why was this closed?

**Comment by dthree** [comment]
I just dont think its being worked on anymore. Vorpal needs an overhaul, which I will be doing at some point in the future and addressing all issues.

**Comment by ShadiestGoat** [comment]
Hey, if you will be working on that, can you open an issue with a list of fixes? Do you plan on making it in Typescript?

**Comment by milesj** [comment]
I went ahead and just built my own CLI: https://boostlib.dev/docs/cli

**Pull request closed without merging**
