### PR TITLE
Better argument parsing #49

### PR DESCRIPTION
**Pull request by scotthovestadt**

### CODE REVIEW

**Comment by dthree** [comment]
Thanks! As this is a bit touchy in that it can easily break things, could you throw in some tests for this?

**Comment by scotthovestadt** [comment]
All of the existing tests pass which means that it's pretty certain to work, but I can add some more tests, specifically around using single quotes inside of double quotes, etc.

**Comment by scotthovestadt** [comment]
@dthree I've added tests. Please merge in and release new package if everything looks good to you.

**Comment by dthree** [comment]
You're awesome!

:+1:

**Pull request merged**
