### PR TITLE
fix using session delimiter as function not string

### PR DESCRIPTION
**Pull request by mvayngrib**

### CODE REVIEW

**Comment by scotthovestadt** [comment]
Looks good to me if I'm understanding the code correctly. @dthree ?

**Comment by dthree** [comment]
This looks fine, but I'm totally puzzled as to how this even worked before - it seems like passing in a function would throw an obvious error or make the delimiter a `function` string.

@mvayngrib :+1: on catching and fixing this, however can you please tell me what behavior led you to finding this, and how this behavior is different now? Thanks.

**Comment by mvayngrib** [comment]
@dthree i was hitting Ctrl+C mid-command and it printed a function on the screen. I searched for the function in the vorpal code and saw it was the delimiter function

**Comment by dthree** [comment]
Haha - got it. Thanks a lot for the fix!

**Comment by mvayngrib** [comment]
thanks for the lib!

**Comment by dthree** [comment]
:+1:

**Pull request merged**
