### PR TITLE
Fixed missing attach for parse function.

### PR DESCRIPTION
**Pull request by alansouzati**
Fixes https://github.com/dthree/vorpal/issues/164.

It turns out that if I add attach function everything works as expected because now UI module has a parent inside the prompt function.

### CODE REVIEW

**Comment by dthree** [comment]
Good find. :+1:

**Comment by alansouzati** [comment]
Cool, thanks for the fast follow up. Could please release a new version of vorpal? I'm kind of dependent on this fix to release our new CLI 💃

**Comment by dthree** [comment]
Pushed to `v1.11.3`. :tada:

**Comment by alansouzati** [comment]
🍻

**Comment by ruyadorno** [comment]
@alansouzati and @dthree just a small follow up from this PR 😊 

I manage an internal cli app that used to rely on `vorpal.parse` mechanism to just forward commands to its vorpal actions and exit the process right away.

After this PR landed, this "command forwarding" flow is not so nice as it used to be, as the process will be kept alive by having an attached ui and users now need an extra CTRL+C to exit the app after a command ran - in the meantime I found a solution by monkey-patching `vorpal.ui.attach`to preserve the same functionality as before. e.g:

```js
if (process.argv.length > 2) {
	cli.ui.attach = () => {};
	cli.parse(process.argv);
}
```

So my question is: Was our previous usage a non-standard and therefore non-supported way of consuming the **vorpal** API? Is there a better/correct syntax to implement the same functionality (non-interactive commands that just execute their logic and exit right after).

Any insights would be very much appreciated, thanks for your time!

**Comment by alansouzati** [comment]
I'm facing the same issue. See this PR I sent: 

https://github.com/dthree/vorpal/pull/169

**Comment by dthree** [comment]
Hmmm... okay. I see this. More in the PR.

**Pull request merged**
