### PR TITLE
Fix for undefined check

### LINKED ISSUE #167: Undefined is being printed after latest release
Whenever my vorpal is displayed I'm experiencing the scenario where I have the delimiter plus an undefined into parenthesis:

```command
grommet~$ (undefined)
```

It seems this was an issue introduced after this commit:https://github.com/dthree/vorpal/commit/f8646d0a3b31630396f2cf64e5075e10e4e60835

The idea I guess is to show the default value for prompts, which is really nice. I believe the check should not be only for null, but for undefined as well.

### PR DESCRIPTION
**Pull request by alansouzati**
Fixes #167

### CODE REVIEW

**Comment by zakhenry** [comment]
Oops that was my mistake, only possible concern is that for a prompt that has a default of `false`, the default won't be output, but that is an edge case that should be addressed after this fix is merged.

**Comment by alansouzati** [comment]
thanks for the heads-up on the false corner case @zakhenry. I've updated this PR with the fix for that as well.

**Comment by alansouzati** [comment]
hey @dthree would appreciate your insights here 😄

**Comment by dthree** [comment]
Looks really good, thanks for the PR! :+1:

**Comment by dthree** [comment]
Pushed in `v1.11.14`.

**Pull request merged**
